apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: |2-

      Plasma App kube version 1.0
  creationTimestamp: "2022-11-18T05:54:08Z"
  generation: 1
  labels:
    k8s-app: plasma-donor-app-53045
  name: plasma-donor-app-53045
  namespace: default
  resourceVersion: "329123"
  uid: 295f85c7-8aa7-4b3a-9cc1-5a57e4db17cc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: plasma-donor-app-53045
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: |2-

          Plasma App kube version 1.0
      creationTimestamp: null
      labels:
        k8s-app: plasma-donor-app-53045
      name: plasma-donor-app-53045
    spec:
      containers:
        - image: au.icr.io/plasma-donor-app/pdapp-repo:v.main.2
          imagePullPolicy: IfNotPresent
          name: plasma-donor-app-53045
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2022-11-18T05:55:04Z"
      lastUpdateTime: "2022-11-18T05:55:04Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-11-18T05:54:08Z"
      lastUpdateTime: "2022-11-18T05:55:04Z"
      message: ReplicaSet "plasma-donor-app-53045-b9d9b57d8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
